[package]
name = "montyformat"
version = "0.9.1"
edition = "2021"
authors = ["Jamie Whiting"]
description = "Compressed data formats for Monty"
license = "AGPL-3.0"

[profile.release]
panic = 'abort'
strip = true
lto = true
codegen-units = 1
